### ISSUE TITLE
Please update electron-builder

### ISSUE THREAD

**Issue by probonopd** [denysdovhan/inboxer#7]
Please update electron-builder to the latest version so that the generated AppImage gets the correct magic bytes. 

To verify, run `xxd Some.AppImage | head -n 1` - it must show the [AppImage type-2 magic bytes](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format) `0x414902`:

*  `0000000: 7f45 4c46 0101 0100 4149 0200 0000 0000  .ELF....AI......`  __correct__, whereas 
*  `0000000: 7f45 4c46 0101 0100 0000 0000 0000 0000  .ELF............` __broken__.

Thanks.

References:
* https://github.com/AppImage/appimage.github.io/pull/189
* https://github.com/electron-userland/electron-builder-binaries/issues/6

**Comment by denysdovhan** [comment]
Should be fixed by #44. Thanks!

**Comment by probonopd** [comment]
If someone would be so nice to ping me once a release containing this fix is out, then I could add it to the AppImageHub central directory of available AppImages. Thanks.

**Comment by denysdovhan** [comment]
@probonopd [`v1.1.0`](https://github.com/denysdovhan/inboxer/releases/tag/v1.1.0) just released.

**Comment by probonopd** [comment]
Strange, still getting the same error.

https://travis-ci.org/AppImage/appimage.github.io/builds/366545551#L93
